name: innowatt
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  file_picker: ^8.0.3
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_analytics: ^11.1.0
  http: ^1.2.2
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  path: ^1.9.0
  share_plus: ^9.0.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.14
  google_fonts: ^6.2.1
  meta: ^1.12.0
  image_picker: ^1.1.2
  mime: ^1.0.5
  open_filex: ^4.4.0
  firebase_storage: ^12.1.1
  equatable: ^2.0.5
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/avatar.png