// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5Bsbha_1dE06IQi05Pjd7FA0MsAsk87g',
    appId: '1:682609745797:android:f287b08108b0770db46eec',
    messagingSenderId: '682609745797',
    projectId: 'innowatt-app',
    storageBucket: 'innowatt-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACDf0YQ1ezDwE_QltyJsdyn2xCWgou_8Y',
    appId: '1:682609745797:ios:f7a4674a7d9de43fb46eec',
    messagingSenderId: '682609745797',
    projectId: 'innowatt-app',
    storageBucket: 'innowatt-app.appspot.com',
    iosBundleId: 'com.atozdecisions.innowatt',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj24HC93Mp4Tq507WPXQogrRgFN_TgPMU',
    appId: '1:682609745797:web:bf618269336da51ab46eec',
    messagingSenderId: '682609745797',
    projectId: 'innowatt-app',
    authDomain: 'innowatt-app.firebaseapp.com',
    storageBucket: 'innowatt-app.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACDf0YQ1ezDwE_QltyJsdyn2xCWgou_8Y',
    appId: '1:682609745797:ios:f7a4674a7d9de43fb46eec',
    messagingSenderId: '682609745797',
    projectId: 'innowatt-app',
    storageBucket: 'innowatt-app.appspot.com',
    iosBundleId: 'com.atozdecisions.innowatt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj24HC93Mp4Tq507WPXQogrRgFN_TgPMU',
    appId: '1:682609745797:web:99de28c61f242f9bb46eec',
    messagingSenderId: '682609745797',
    projectId: 'innowatt-app',
    authDomain: 'innowatt-app.firebaseapp.com',
    storageBucket: 'innowatt-app.appspot.com',
  );

}